#include "min_and_max.h"
#include "unit_testing.h"
#include "alternative_operators.h"

TEST(min_char_tests, "Minimum char")
{
	ASSERT_INT_EQUAL(min_char(CHAR_MIN, CHAR_MIN), CHAR_MIN);
	ASSERT_INT_EQUAL(min_char(CHAR_MIN, CHAR_MAX), CHAR_MIN);
	ASSERT_INT_EQUAL(min_char(0, 0), 0);
	ASSERT_INT_EQUAL(min_char(0, CHAR_MAX), 0);
	ASSERT_INT_EQUAL(min_char(CHAR_MAX, CHAR_MIN), CHAR_MIN);
	ASSERT_INT_EQUAL(min_char(CHAR_MAX, 0), 0);
	ASSERT_INT_EQUAL(min_char(CHAR_MAX, CHAR_MAX), CHAR_MAX);
}

TEST(max_char_tests, "Maximum char")
{
	ASSERT_INT_EQUAL(max_char(CHAR_MIN, CHAR_MIN), CHAR_MIN);
	ASSERT_INT_EQUAL(max_char(CHAR_MIN, CHAR_MAX), CHAR_MAX);
	ASSERT_INT_EQUAL(max_char(0, 0), 0);
	ASSERT_INT_EQUAL(max_char(0, CHAR_MAX), CHAR_MAX);
	ASSERT_INT_EQUAL(max_char(CHAR_MAX, CHAR_MIN), CHAR_MAX);
	ASSERT_INT_EQUAL(max_char(CHAR_MAX, 0), CHAR_MAX);
	ASSERT_INT_EQUAL(max_char(CHAR_MAX, CHAR_MAX), CHAR_MAX);
}

TEST(min_schar_tests, "Minimum signed char")
{
	ASSERT_INT_EQUAL(min_schar(SCHAR_MIN, SCHAR_MIN), SCHAR_MIN);
	ASSERT_INT_EQUAL(min_schar(SCHAR_MIN, -1), SCHAR_MIN);
	ASSERT_INT_EQUAL(min_schar(SCHAR_MIN, 0), SCHAR_MIN);
	ASSERT_INT_EQUAL(min_schar(SCHAR_MIN, 1), SCHAR_MIN);
	ASSERT_INT_EQUAL(min_schar(SCHAR_MIN, SCHAR_MAX), SCHAR_MIN);

	ASSERT_INT_EQUAL(min_schar(-1, SCHAR_MIN), SCHAR_MIN);
	ASSERT_INT_EQUAL(min_schar(-1, -1), -1);
	ASSERT_INT_EQUAL(min_schar(-1, 0), -1);
	ASSERT_INT_EQUAL(min_schar(-1, 1), -1);
	ASSERT_INT_EQUAL(min_schar(-1, SCHAR_MAX), -1);

	ASSERT_INT_EQUAL(min_schar(0, SCHAR_MIN), SCHAR_MIN);
	ASSERT_INT_EQUAL(min_schar(0, -1), -1);
	ASSERT_INT_EQUAL(min_schar(0, 0), 0);
	ASSERT_INT_EQUAL(min_schar(0, 1), 0);
	ASSERT_INT_EQUAL(min_schar(0, SCHAR_MAX), 0);

	ASSERT_INT_EQUAL(min_schar(1, SCHAR_MIN), SCHAR_MIN);
	ASSERT_INT_EQUAL(min_schar(1, -1), -1);
	ASSERT_INT_EQUAL(min_schar(1, 0), 0);
	ASSERT_INT_EQUAL(min_schar(1, 1), 1);
	ASSERT_INT_EQUAL(min_schar(1, SCHAR_MAX), 1);

	ASSERT_INT_EQUAL(min_schar(SCHAR_MAX, SCHAR_MIN), SCHAR_MIN);
	ASSERT_INT_EQUAL(min_schar(SCHAR_MAX, -1), -1);
	ASSERT_INT_EQUAL(min_schar(SCHAR_MAX, 0), 0);
	ASSERT_INT_EQUAL(min_schar(SCHAR_MAX, 1), 1);
	ASSERT_INT_EQUAL(min_schar(SCHAR_MAX, SCHAR_MAX), SCHAR_MAX);
}

TEST(max_schar_tests, "Maximum signed char")
{
	ASSERT_INT_EQUAL(max_schar(SCHAR_MIN, SCHAR_MIN), SCHAR_MIN);
	ASSERT_INT_EQUAL(max_schar(SCHAR_MIN, -1), -1);
	ASSERT_INT_EQUAL(max_schar(SCHAR_MIN, 0), 0);
	ASSERT_INT_EQUAL(max_schar(SCHAR_MIN, 1), 1);
	ASSERT_INT_EQUAL(max_schar(SCHAR_MIN, SCHAR_MAX), SCHAR_MAX);

	ASSERT_INT_EQUAL(max_schar(-1, SCHAR_MIN), -1);
	ASSERT_INT_EQUAL(max_schar(-1, -1), -1);
	ASSERT_INT_EQUAL(max_schar(-1, 0), 0);
	ASSERT_INT_EQUAL(max_schar(-1, 1), 1);
	ASSERT_INT_EQUAL(max_schar(-1, SCHAR_MAX), SCHAR_MAX);

	ASSERT_INT_EQUAL(max_schar(0, SCHAR_MIN), 0);
	ASSERT_INT_EQUAL(max_schar(0, -1), 0);
	ASSERT_INT_EQUAL(max_schar(0, 0), 0);
	ASSERT_INT_EQUAL(max_schar(0, 1), 1);
	ASSERT_INT_EQUAL(max_schar(0, SCHAR_MAX), SCHAR_MAX);

	ASSERT_INT_EQUAL(max_schar(1, SCHAR_MIN), 1);
	ASSERT_INT_EQUAL(max_schar(1, -1), 1);
	ASSERT_INT_EQUAL(max_schar(1, 0), 1);
	ASSERT_INT_EQUAL(max_schar(1, 1), 1);
	ASSERT_INT_EQUAL(max_schar(1, SCHAR_MAX), SCHAR_MAX);

	ASSERT_INT_EQUAL(max_schar(SCHAR_MAX, SCHAR_MIN), SCHAR_MAX);
	ASSERT_INT_EQUAL(max_schar(SCHAR_MAX, -1), SCHAR_MAX);
	ASSERT_INT_EQUAL(max_schar(SCHAR_MAX, 0), SCHAR_MAX);
	ASSERT_INT_EQUAL(max_schar(SCHAR_MAX, 1), SCHAR_MAX);
	ASSERT_INT_EQUAL(max_schar(SCHAR_MAX, SCHAR_MAX), SCHAR_MAX);
}

TEST(min_uchar_tests, "Minimum unsigned char")
{
	ASSERT_INT_EQUAL(min_uchar(0U, 0U), 0U);
	ASSERT_INT_EQUAL(min_uchar(0U, 1U), 0U);
	ASSERT_INT_EQUAL(min_uchar(0U, UCHAR_MAX), 0U);

	ASSERT_INT_EQUAL(min_uchar(1U, 0U), 0U);
	ASSERT_INT_EQUAL(min_uchar(1U, 1U), 1U);
	ASSERT_INT_EQUAL(min_uchar(1U, UCHAR_MAX), 1U);

	ASSERT_INT_EQUAL(min_uchar(UCHAR_MAX, 0U), 0U);
	ASSERT_INT_EQUAL(min_uchar(UCHAR_MAX, 1U), 1U);
	ASSERT_INT_EQUAL(min_uchar(UCHAR_MAX, UCHAR_MAX), UCHAR_MAX);
}

TEST(max_uchar_tests, "Maximum unsigned char")
{
	ASSERT_INT_EQUAL(max_uchar(0U, 0U), 0U);
	ASSERT_INT_EQUAL(max_uchar(0U, 1U), 1U);
	ASSERT_INT_EQUAL(max_uchar(0U, UCHAR_MAX), UCHAR_MAX);

	ASSERT_INT_EQUAL(max_uchar(1U, 0U), 1U);
	ASSERT_INT_EQUAL(max_uchar(1U, 1U), 1U);
	ASSERT_INT_EQUAL(max_uchar(1U, UCHAR_MAX), UCHAR_MAX);

	ASSERT_INT_EQUAL(max_uchar(UCHAR_MAX, 0U), UCHAR_MAX);
	ASSERT_INT_EQUAL(max_uchar(UCHAR_MAX, 1U), UCHAR_MAX);
	ASSERT_INT_EQUAL(max_uchar(UCHAR_MAX, UCHAR_MAX), UCHAR_MAX);
}

TEST(min_short_tests, "Minimum short")
{
	ASSERT_INT_EQUAL(min_short(SHRT_MIN, SHRT_MIN), SHRT_MIN);
	ASSERT_INT_EQUAL(min_short(SHRT_MIN, -1), SHRT_MIN);
	ASSERT_INT_EQUAL(min_short(SHRT_MIN, 0), SHRT_MIN);
	ASSERT_INT_EQUAL(min_short(SHRT_MIN, 1), SHRT_MIN);
	ASSERT_INT_EQUAL(min_short(SHRT_MIN, SHRT_MAX), SHRT_MIN);

	ASSERT_INT_EQUAL(min_short(-1, SHRT_MIN), SHRT_MIN);
	ASSERT_INT_EQUAL(min_short(-1, -1), -1);
	ASSERT_INT_EQUAL(min_short(-1, 0), -1);
	ASSERT_INT_EQUAL(min_short(-1, 1), -1);
	ASSERT_INT_EQUAL(min_short(-1, SHRT_MAX), -1);

	ASSERT_INT_EQUAL(min_short(0, SHRT_MIN), SHRT_MIN);
	ASSERT_INT_EQUAL(min_short(0, -1), -1);
	ASSERT_INT_EQUAL(min_short(0, 0), 0);
	ASSERT_INT_EQUAL(min_short(0, 1), 0);
	ASSERT_INT_EQUAL(min_short(0, SHRT_MAX), 0);

	ASSERT_INT_EQUAL(min_short(1, SHRT_MIN), SHRT_MIN);
	ASSERT_INT_EQUAL(min_short(1, -1), -1);
	ASSERT_INT_EQUAL(min_short(1, 0), 0);
	ASSERT_INT_EQUAL(min_short(1, 1), 1);
	ASSERT_INT_EQUAL(min_short(1, SHRT_MAX), 1);

	ASSERT_INT_EQUAL(min_short(SHRT_MAX, SHRT_MIN), SHRT_MIN);
	ASSERT_INT_EQUAL(min_short(SHRT_MAX, -1), -1);
	ASSERT_INT_EQUAL(min_short(SHRT_MAX, 0), 0);
	ASSERT_INT_EQUAL(min_short(SHRT_MAX, 1), 1);
	ASSERT_INT_EQUAL(min_short(SHRT_MAX, SHRT_MAX), SHRT_MAX);
}

TEST(max_short_tests, "Maximum short")
{
	ASSERT_INT_EQUAL(max_short(SHRT_MIN, SHRT_MIN), SHRT_MIN);
	ASSERT_INT_EQUAL(max_short(SHRT_MIN, -1), -1);
	ASSERT_INT_EQUAL(max_short(SHRT_MIN, 0), 0);
	ASSERT_INT_EQUAL(max_short(SHRT_MIN, 1), 1);
	ASSERT_INT_EQUAL(max_short(SHRT_MIN, SHRT_MAX), SHRT_MAX);

	ASSERT_INT_EQUAL(max_short(-1, SHRT_MIN), -1);
	ASSERT_INT_EQUAL(max_short(-1, -1), -1);
	ASSERT_INT_EQUAL(max_short(-1, 0), 0);
	ASSERT_INT_EQUAL(max_short(-1, 1), 1);
	ASSERT_INT_EQUAL(max_short(-1, SHRT_MAX), SHRT_MAX);

	ASSERT_INT_EQUAL(max_short(0, SHRT_MIN), 0);
	ASSERT_INT_EQUAL(max_short(0, -1), 0);
	ASSERT_INT_EQUAL(max_short(0, 0), 0);
	ASSERT_INT_EQUAL(max_short(0, 1), 1);
	ASSERT_INT_EQUAL(max_short(0, SHRT_MAX), SHRT_MAX);

	ASSERT_INT_EQUAL(max_short(1, SHRT_MIN), 1);
	ASSERT_INT_EQUAL(max_short(1, -1), 1);
	ASSERT_INT_EQUAL(max_short(1, 0), 1);
	ASSERT_INT_EQUAL(max_short(1, 1), 1);
	ASSERT_INT_EQUAL(max_short(1, SHRT_MAX), SHRT_MAX);

	ASSERT_INT_EQUAL(max_short(SHRT_MAX, SHRT_MIN), SHRT_MAX);
	ASSERT_INT_EQUAL(max_short(SHRT_MAX, -1), SHRT_MAX);
	ASSERT_INT_EQUAL(max_short(SHRT_MAX, 0), SHRT_MAX);
	ASSERT_INT_EQUAL(max_short(SHRT_MAX, 1), SHRT_MAX);
	ASSERT_INT_EQUAL(max_short(SHRT_MAX, SHRT_MAX), SHRT_MAX);
}

TEST(min_ushort_tests, "Minimum unsigned short")
{
	ASSERT_UINT_EQUAL(min_ushort(0U, 0U), 0U);
	ASSERT_UINT_EQUAL(min_ushort(0U, 1U), 0U);
	ASSERT_UINT_EQUAL(min_ushort(0U, USHRT_MAX), 0U);

	ASSERT_UINT_EQUAL(min_ushort(1U, 0U), 0U);
	ASSERT_UINT_EQUAL(min_ushort(1U, 1U), 1U);
	ASSERT_UINT_EQUAL(min_ushort(1U, USHRT_MAX), 1U);

	ASSERT_UINT_EQUAL(min_ushort(USHRT_MAX, 0U), 0U);
	ASSERT_UINT_EQUAL(min_ushort(USHRT_MAX, 1U), 1U);
	ASSERT_UINT_EQUAL(min_ushort(USHRT_MAX, USHRT_MAX), USHRT_MAX);
}

TEST(max_ushort_tests, "Maximum unsigned short")
{
	ASSERT_UINT_EQUAL(max_ushort(0U, 0U), 0U);
	ASSERT_UINT_EQUAL(max_ushort(0U, 1U), 1U);
	ASSERT_UINT_EQUAL(max_ushort(0U, USHRT_MAX), USHRT_MAX);

	ASSERT_UINT_EQUAL(max_ushort(1U, 0U), 1U);
	ASSERT_UINT_EQUAL(max_ushort(1U, 1U), 1U);
	ASSERT_UINT_EQUAL(max_ushort(1U, USHRT_MAX), USHRT_MAX);

	ASSERT_UINT_EQUAL(max_ushort(USHRT_MAX, 0U), USHRT_MAX);
	ASSERT_UINT_EQUAL(max_ushort(USHRT_MAX, 1U), USHRT_MAX);
	ASSERT_UINT_EQUAL(max_ushort(USHRT_MAX, USHRT_MAX), USHRT_MAX);
}

TEST(min_int_tests, "Minimum int")
{
	ASSERT_INT_EQUAL(min_int(INT_MIN, INT_MIN), INT_MIN);
	ASSERT_INT_EQUAL(min_int(INT_MIN, -1), INT_MIN);
	ASSERT_INT_EQUAL(min_int(INT_MIN, 0), INT_MIN);
	ASSERT_INT_EQUAL(min_int(INT_MIN, 1), INT_MIN);
	ASSERT_INT_EQUAL(min_int(INT_MIN, INT_MAX), INT_MIN);

	ASSERT_INT_EQUAL(min_int(-1, INT_MIN), INT_MIN);
	ASSERT_INT_EQUAL(min_int(-1, -1), -1);
	ASSERT_INT_EQUAL(min_int(-1, 0), -1);
	ASSERT_INT_EQUAL(min_int(-1, 1), -1);
	ASSERT_INT_EQUAL(min_int(-1, INT_MAX), -1);

	ASSERT_INT_EQUAL(min_int(0, INT_MIN), INT_MIN);
	ASSERT_INT_EQUAL(min_int(0, -1), -1);
	ASSERT_INT_EQUAL(min_int(0, 0), 0);
	ASSERT_INT_EQUAL(min_int(0, 1), 0);
	ASSERT_INT_EQUAL(min_int(0, INT_MAX), 0);

	ASSERT_INT_EQUAL(min_int(1, INT_MIN), INT_MIN);
	ASSERT_INT_EQUAL(min_int(1, -1), -1);
	ASSERT_INT_EQUAL(min_int(1, 0), 0);
	ASSERT_INT_EQUAL(min_int(1, 1), 1);
	ASSERT_INT_EQUAL(min_int(1, INT_MAX), 1);

	ASSERT_INT_EQUAL(min_int(INT_MAX, INT_MIN), INT_MIN);
	ASSERT_INT_EQUAL(min_int(INT_MAX, -1), -1);
	ASSERT_INT_EQUAL(min_int(INT_MAX, 0), 0);
	ASSERT_INT_EQUAL(min_int(INT_MAX, 1), 1);
	ASSERT_INT_EQUAL(min_int(INT_MAX, INT_MAX), INT_MAX);
}

TEST(max_int_tests, "Maximum int")
{
	ASSERT_INT_EQUAL(max_int(INT_MIN, INT_MIN), INT_MIN);
	ASSERT_INT_EQUAL(max_int(INT_MIN, -1), -1);
	ASSERT_INT_EQUAL(max_int(INT_MIN, 0), 0);
	ASSERT_INT_EQUAL(max_int(INT_MIN, 1), 1);
	ASSERT_INT_EQUAL(max_int(INT_MIN, INT_MAX), INT_MAX);

	ASSERT_INT_EQUAL(max_int(-1, INT_MIN), -1);
	ASSERT_INT_EQUAL(max_int(-1, -1), -1);
	ASSERT_INT_EQUAL(max_int(-1, 0), 0);
	ASSERT_INT_EQUAL(max_int(-1, 1), 1);
	ASSERT_INT_EQUAL(max_int(-1, INT_MAX), INT_MAX);

	ASSERT_INT_EQUAL(max_int(0, INT_MIN), 0);
	ASSERT_INT_EQUAL(max_int(0, -1), 0);
	ASSERT_INT_EQUAL(max_int(0, 0), 0);
	ASSERT_INT_EQUAL(max_int(0, 1), 1);
	ASSERT_INT_EQUAL(max_int(0, INT_MAX), INT_MAX);

	ASSERT_INT_EQUAL(max_int(1, INT_MIN), 1);
	ASSERT_INT_EQUAL(max_int(1, -1), 1);
	ASSERT_INT_EQUAL(max_int(1, 0), 1);
	ASSERT_INT_EQUAL(max_int(1, 1), 1);
	ASSERT_INT_EQUAL(max_int(1, INT_MAX), INT_MAX);

	ASSERT_INT_EQUAL(max_int(INT_MAX, INT_MIN), INT_MAX);
	ASSERT_INT_EQUAL(max_int(INT_MAX, -1), INT_MAX);
	ASSERT_INT_EQUAL(max_int(INT_MAX, 0), INT_MAX);
	ASSERT_INT_EQUAL(max_int(INT_MAX, 1), INT_MAX);
	ASSERT_INT_EQUAL(max_int(INT_MAX, INT_MAX), INT_MAX);
}

TEST(min_uint_tests, "Minimum unsigned int")
{
	ASSERT_UINT_EQUAL(min_uint(0U, 0U), 0U);
	ASSERT_UINT_EQUAL(min_uint(0U, 1U), 0U);
	ASSERT_UINT_EQUAL(min_uint(0U, UINT_MAX), 0U);

	ASSERT_UINT_EQUAL(min_uint(1U, 0U), 0U);
	ASSERT_UINT_EQUAL(min_uint(1U, 1U), 1U);
	ASSERT_UINT_EQUAL(min_uint(1U, UINT_MAX), 1U);

	ASSERT_UINT_EQUAL(min_uint(UINT_MAX, 0U), 0U);
	ASSERT_UINT_EQUAL(min_uint(UINT_MAX, 1U), 1U);
	ASSERT_UINT_EQUAL(min_uint(UINT_MAX, UINT_MAX), UINT_MAX);
}

TEST(max_uint_tests, "Maximum unsigned int")
{
	ASSERT_UINT_EQUAL(max_uint(0U, 0U), 0U);
	ASSERT_UINT_EQUAL(max_uint(0U, 1U), 1U);
	ASSERT_UINT_EQUAL(max_uint(0U, UINT_MAX), UINT_MAX);

	ASSERT_UINT_EQUAL(max_uint(1U, 0U), 1U);
	ASSERT_UINT_EQUAL(max_uint(1U, 1U), 1U);
	ASSERT_UINT_EQUAL(max_uint(1U, UINT_MAX), UINT_MAX);

	ASSERT_UINT_EQUAL(max_uint(UINT_MAX, 0U), UINT_MAX);
	ASSERT_UINT_EQUAL(max_uint(UINT_MAX, 1U), UINT_MAX);
	ASSERT_UINT_EQUAL(max_uint(UINT_MAX, UINT_MAX), UINT_MAX);
}

TEST(min_long_tests, "Minimum long")
{
	ASSERT_LONG_EQUAL(min_long(LONG_MIN, LONG_MIN), LONG_MIN);
	ASSERT_LONG_EQUAL(min_long(LONG_MIN, -1), LONG_MIN);
	ASSERT_LONG_EQUAL(min_long(LONG_MIN, 0), LONG_MIN);
	ASSERT_LONG_EQUAL(min_long(LONG_MIN, 1), LONG_MIN);
	ASSERT_LONG_EQUAL(min_long(LONG_MIN, LONG_MAX), LONG_MIN);

	ASSERT_LONG_EQUAL(min_long(-1, LONG_MIN), LONG_MIN);
	ASSERT_LONG_EQUAL(min_long(-1, -1), -1);
	ASSERT_LONG_EQUAL(min_long(-1, 0), -1);
	ASSERT_LONG_EQUAL(min_long(-1, 1), -1);
	ASSERT_LONG_EQUAL(min_long(-1, LONG_MAX), -1);

	ASSERT_LONG_EQUAL(min_long(0, LONG_MIN), LONG_MIN);
	ASSERT_LONG_EQUAL(min_long(0, -1), -1);
	ASSERT_LONG_EQUAL(min_long(0, 0), 0);
	ASSERT_LONG_EQUAL(min_long(0, 1), 0);
	ASSERT_LONG_EQUAL(min_long(0, LONG_MAX), 0);

	ASSERT_LONG_EQUAL(min_long(1, LONG_MIN), LONG_MIN);
	ASSERT_LONG_EQUAL(min_long(1, -1), -1);
	ASSERT_LONG_EQUAL(min_long(1, 0), 0);
	ASSERT_LONG_EQUAL(min_long(1, 1), 1);
	ASSERT_LONG_EQUAL(min_long(1, LONG_MAX), 1);

	ASSERT_LONG_EQUAL(min_long(LONG_MAX, LONG_MIN), LONG_MIN);
	ASSERT_LONG_EQUAL(min_long(LONG_MAX, -1), -1);
	ASSERT_LONG_EQUAL(min_long(LONG_MAX, 0), 0);
	ASSERT_LONG_EQUAL(min_long(LONG_MAX, 1), 1);
	ASSERT_LONG_EQUAL(min_long(LONG_MAX, LONG_MAX), LONG_MAX);
}

TEST(max_long_tests, "Maximum long")
{
	ASSERT_LONG_EQUAL(max_long(LONG_MIN, LONG_MIN), LONG_MIN);
	ASSERT_LONG_EQUAL(max_long(LONG_MIN, -1), -1);
	ASSERT_LONG_EQUAL(max_long(LONG_MIN, 0), 0);
	ASSERT_LONG_EQUAL(max_long(LONG_MIN, 1), 1);
	ASSERT_LONG_EQUAL(max_long(LONG_MIN, LONG_MAX), LONG_MAX);

	ASSERT_LONG_EQUAL(max_long(-1, LONG_MIN), -1);
	ASSERT_LONG_EQUAL(max_long(-1, -1), -1);
	ASSERT_LONG_EQUAL(max_long(-1, 0), 0);
	ASSERT_LONG_EQUAL(max_long(-1, 1), 1);
	ASSERT_LONG_EQUAL(max_long(-1, LONG_MAX), LONG_MAX);

	ASSERT_LONG_EQUAL(max_long(0, LONG_MIN), 0);
	ASSERT_LONG_EQUAL(max_long(0, -1), 0);
	ASSERT_LONG_EQUAL(max_long(0, 0), 0);
	ASSERT_LONG_EQUAL(max_long(0, 1), 1);
	ASSERT_LONG_EQUAL(max_long(0, LONG_MAX), LONG_MAX);

	ASSERT_LONG_EQUAL(max_long(1, LONG_MIN), 1);
	ASSERT_LONG_EQUAL(max_long(1, -1), 1);
	ASSERT_LONG_EQUAL(max_long(1, 0), 1);
	ASSERT_LONG_EQUAL(max_long(1, 1), 1);
	ASSERT_LONG_EQUAL(max_long(1, LONG_MAX), LONG_MAX);

	ASSERT_LONG_EQUAL(max_long(LONG_MAX, LONG_MIN), LONG_MAX);
	ASSERT_LONG_EQUAL(max_long(LONG_MAX, -1), LONG_MAX);
	ASSERT_LONG_EQUAL(max_long(LONG_MAX, 0), LONG_MAX);
	ASSERT_LONG_EQUAL(max_long(LONG_MAX, 1), LONG_MAX);
	ASSERT_LONG_EQUAL(max_long(LONG_MAX, LONG_MAX), LONG_MAX);
}

TEST(min_ulong_tests, "Minimum unsigned long")
{
	ASSERT_ULONG_EQUAL(min_ulong(0U, 0U), 0U);
	ASSERT_ULONG_EQUAL(min_ulong(0U, 1U), 0U);
	ASSERT_ULONG_EQUAL(min_ulong(0U, ULONG_MAX), 0U);

	ASSERT_ULONG_EQUAL(min_ulong(1U, 0U), 0U);
	ASSERT_ULONG_EQUAL(min_ulong(1U, 1U), 1U);
	ASSERT_ULONG_EQUAL(min_ulong(1U, ULONG_MAX), 1U);

	ASSERT_ULONG_EQUAL(min_ulong(ULONG_MAX, 0U), 0U);
	ASSERT_ULONG_EQUAL(min_ulong(ULONG_MAX, 1U), 1U);
	ASSERT_ULONG_EQUAL(min_ulong(ULONG_MAX, ULONG_MAX), ULONG_MAX);
}

TEST(max_ulong_tests, "Maximum unsigned long")
{
	ASSERT_ULONG_EQUAL(max_ulong(0U, 0U), 0U);
	ASSERT_ULONG_EQUAL(max_ulong(0U, 1U), 1U);
	ASSERT_ULONG_EQUAL(max_ulong(0U, ULONG_MAX), ULONG_MAX);

	ASSERT_ULONG_EQUAL(max_ulong(1U, 0U), 1U);
	ASSERT_ULONG_EQUAL(max_ulong(1U, 1U), 1U);
	ASSERT_ULONG_EQUAL(max_ulong(1U, ULONG_MAX), ULONG_MAX);

	ASSERT_ULONG_EQUAL(max_ulong(ULONG_MAX, 0U), ULONG_MAX);
	ASSERT_ULONG_EQUAL(max_ulong(ULONG_MAX, 1U), ULONG_MAX);
	ASSERT_ULONG_EQUAL(max_ulong(ULONG_MAX, ULONG_MAX), ULONG_MAX);
}

#if defined(LLONG_MIN) and defined(LLONG_MAX)

TEST(min_llong_tests, "Minimum long long")
{
	ASSERT_LLONG_EQUAL(min_llong(LLONG_MIN, LLONG_MIN), LLONG_MIN);
	ASSERT_LLONG_EQUAL(min_llong(LLONG_MIN, -1), LLONG_MIN);
	ASSERT_LLONG_EQUAL(min_llong(LLONG_MIN, 0), LLONG_MIN);
	ASSERT_LLONG_EQUAL(min_llong(LLONG_MIN, 1), LLONG_MIN);
	ASSERT_LLONG_EQUAL(min_llong(LLONG_MIN, LLONG_MAX), LLONG_MIN);

	ASSERT_LLONG_EQUAL(min_llong(-1, LLONG_MIN), LLONG_MIN);
	ASSERT_LLONG_EQUAL(min_llong(-1, -1), -1);
	ASSERT_LLONG_EQUAL(min_llong(-1, 0), -1);
	ASSERT_LLONG_EQUAL(min_llong(-1, 1), -1);
	ASSERT_LLONG_EQUAL(min_llong(-1, LLONG_MAX), -1);

	ASSERT_LLONG_EQUAL(min_llong(0, LLONG_MIN), LLONG_MIN);
	ASSERT_LLONG_EQUAL(min_llong(0, -1), -1);
	ASSERT_LLONG_EQUAL(min_llong(0, 0), 0);
	ASSERT_LLONG_EQUAL(min_llong(0, 1), 0);
	ASSERT_LLONG_EQUAL(min_llong(0, LLONG_MAX), 0);

	ASSERT_LLONG_EQUAL(min_llong(1, LLONG_MIN), LLONG_MIN);
	ASSERT_LLONG_EQUAL(min_llong(1, -1), -1);
	ASSERT_LLONG_EQUAL(min_llong(1, 0), 0);
	ASSERT_LLONG_EQUAL(min_llong(1, 1), 1);
	ASSERT_LLONG_EQUAL(min_llong(1, LLONG_MAX), 1);

	ASSERT_LLONG_EQUAL(min_llong(LLONG_MAX, LLONG_MIN), LLONG_MIN);
	ASSERT_LLONG_EQUAL(min_llong(LLONG_MAX, -1), -1);
	ASSERT_LLONG_EQUAL(min_llong(LLONG_MAX, 0), 0);
	ASSERT_LLONG_EQUAL(min_llong(LLONG_MAX, 1), 1);
	ASSERT_LLONG_EQUAL(min_llong(LLONG_MAX, LLONG_MAX), LLONG_MAX);
}

TEST(max_llong_tests, "Maximum long long")
{
	ASSERT_LLONG_EQUAL(max_llong(LLONG_MIN, LLONG_MIN), LLONG_MIN);
	ASSERT_LLONG_EQUAL(max_llong(LLONG_MIN, -1), -1);
	ASSERT_LLONG_EQUAL(max_llong(LLONG_MIN, 0), 0);
	ASSERT_LLONG_EQUAL(max_llong(LLONG_MIN, 1), 1);
	ASSERT_LLONG_EQUAL(max_llong(LLONG_MIN, LLONG_MAX), LLONG_MAX);

	ASSERT_LLONG_EQUAL(max_llong(-1, LLONG_MIN), -1);
	ASSERT_LLONG_EQUAL(max_llong(-1, -1), -1);
	ASSERT_LLONG_EQUAL(max_llong(-1, 0), 0);
	ASSERT_LLONG_EQUAL(max_llong(-1, 1), 1);
	ASSERT_LLONG_EQUAL(max_llong(-1, LLONG_MAX), LLONG_MAX);

	ASSERT_LLONG_EQUAL(max_llong(0, LLONG_MIN), 0);
	ASSERT_LLONG_EQUAL(max_llong(0, -1), 0);
	ASSERT_LLONG_EQUAL(max_llong(0, 0), 0);
	ASSERT_LLONG_EQUAL(max_llong(0, 1), 1);
	ASSERT_LLONG_EQUAL(max_llong(0, LLONG_MAX), LLONG_MAX);

	ASSERT_LLONG_EQUAL(max_llong(1, LLONG_MIN), 1);
	ASSERT_LLONG_EQUAL(max_llong(1, -1), 1);
	ASSERT_LLONG_EQUAL(max_llong(1, 0), 1);
	ASSERT_LLONG_EQUAL(max_llong(1, 1), 1);
	ASSERT_LLONG_EQUAL(max_llong(1, LLONG_MAX), LLONG_MAX);

	ASSERT_LLONG_EQUAL(max_llong(LLONG_MAX, LLONG_MIN), LLONG_MAX);
	ASSERT_LLONG_EQUAL(max_llong(LLONG_MAX, -1), LLONG_MAX);
	ASSERT_LLONG_EQUAL(max_llong(LLONG_MAX, 0), LLONG_MAX);
	ASSERT_LLONG_EQUAL(max_llong(LLONG_MAX, 1), LLONG_MAX);
	ASSERT_LLONG_EQUAL(max_llong(LLONG_MAX, LLONG_MAX), LLONG_MAX);
}

#endif

#if defined(ULLONG_MAX)

TEST(min_ullong_tests, "Minimum unsigned llong")
{
	ASSERT_ULLONG_EQUAL(min_ullong(0U, 0U), 0U);
	ASSERT_ULLONG_EQUAL(min_ullong(0U, 1U), 0U);
	ASSERT_ULLONG_EQUAL(min_ullong(0U, ULLONG_MAX), 0U);

	ASSERT_ULLONG_EQUAL(min_ullong(1U, 0U), 0U);
	ASSERT_ULLONG_EQUAL(min_ullong(1U, 1U), 1U);
	ASSERT_ULLONG_EQUAL(min_ullong(1U, ULLONG_MAX), 1U);

	ASSERT_ULLONG_EQUAL(min_ullong(ULLONG_MAX, 0U), 0U);
	ASSERT_ULLONG_EQUAL(min_ullong(ULLONG_MAX, 1U), 1U);
	ASSERT_ULLONG_EQUAL(min_ullong(ULLONG_MAX, ULLONG_MAX), ULLONG_MAX);
}

TEST(max_ullong_tests, "Maximum unsigned llong")
{
	ASSERT_ULLONG_EQUAL(max_ullong(0U, 0U), 0U);
	ASSERT_ULLONG_EQUAL(max_ullong(0U, 1U), 1U);
	ASSERT_ULLONG_EQUAL(max_ullong(0U, ULLONG_MAX), ULLONG_MAX);

	ASSERT_ULLONG_EQUAL(max_ullong(1U, 0U), 1U);
	ASSERT_ULLONG_EQUAL(max_ullong(1U, 1U), 1U);
	ASSERT_ULLONG_EQUAL(max_ullong(1U, ULLONG_MAX), ULLONG_MAX);

	ASSERT_ULLONG_EQUAL(max_ullong(ULLONG_MAX, 0U), ULLONG_MAX);
	ASSERT_ULLONG_EQUAL(max_ullong(ULLONG_MAX, 1U), ULLONG_MAX);
	ASSERT_ULLONG_EQUAL(max_ullong(ULLONG_MAX, ULLONG_MAX), ULLONG_MAX);
}

#endif

TEST(min_i8_tests, "Minimum int8_t")
{
	ASSERT_INT8_EQUAL(min_i8(INT8_MIN, INT8_MIN), INT8_MIN);
	ASSERT_INT8_EQUAL(min_i8(INT8_MIN, -1), INT8_MIN);
	ASSERT_INT8_EQUAL(min_i8(INT8_MIN, 0), INT8_MIN);
	ASSERT_INT8_EQUAL(min_i8(INT8_MIN, 1), INT8_MIN);
	ASSERT_INT8_EQUAL(min_i8(INT8_MIN, INT8_MAX), INT8_MIN);

	ASSERT_INT8_EQUAL(min_i8(-1, INT8_MIN), INT8_MIN);
	ASSERT_INT8_EQUAL(min_i8(-1, -1), -1);
	ASSERT_INT8_EQUAL(min_i8(-1, 0), -1);
	ASSERT_INT8_EQUAL(min_i8(-1, 1), -1);
	ASSERT_INT8_EQUAL(min_i8(-1, INT8_MAX), -1);

	ASSERT_INT8_EQUAL(min_i8(0, INT8_MIN), INT8_MIN);
	ASSERT_INT8_EQUAL(min_i8(0, -1), -1);
	ASSERT_INT8_EQUAL(min_i8(0, 0), 0);
	ASSERT_INT8_EQUAL(min_i8(0, 1), 0);
	ASSERT_INT8_EQUAL(min_i8(0, INT8_MAX), 0);

	ASSERT_INT8_EQUAL(min_i8(1, INT8_MIN), INT8_MIN);
	ASSERT_INT8_EQUAL(min_i8(1, -1), -1);
	ASSERT_INT8_EQUAL(min_i8(1, 0), 0);
	ASSERT_INT8_EQUAL(min_i8(1, 1), 1);
	ASSERT_INT8_EQUAL(min_i8(1, INT8_MAX), 1);

	ASSERT_INT8_EQUAL(min_i8(INT8_MAX, INT8_MIN), INT8_MIN);
	ASSERT_INT8_EQUAL(min_i8(INT8_MAX, -1), -1);
	ASSERT_INT8_EQUAL(min_i8(INT8_MAX, 0), 0);
	ASSERT_INT8_EQUAL(min_i8(INT8_MAX, 1), 1);
	ASSERT_INT8_EQUAL(min_i8(INT8_MAX, INT8_MAX), INT8_MAX);
}

TEST(max_i8_tests, "Maximum int8_t")
{
	ASSERT_INT8_EQUAL(max_i8(INT8_MIN, INT8_MIN), INT8_MIN);
	ASSERT_INT8_EQUAL(max_i8(INT8_MIN, -1), -1);
	ASSERT_INT8_EQUAL(max_i8(INT8_MIN, 0), 0);
	ASSERT_INT8_EQUAL(max_i8(INT8_MIN, 1), 1);
	ASSERT_INT8_EQUAL(max_i8(INT8_MIN, INT8_MAX), INT8_MAX);

	ASSERT_INT8_EQUAL(max_i8(-1, INT8_MIN), -1);
	ASSERT_INT8_EQUAL(max_i8(-1, -1), -1);
	ASSERT_INT8_EQUAL(max_i8(-1, 0), 0);
	ASSERT_INT8_EQUAL(max_i8(-1, 1), 1);
	ASSERT_INT8_EQUAL(max_i8(-1, INT8_MAX), INT8_MAX);

	ASSERT_INT8_EQUAL(max_i8(0, INT8_MIN), 0);
	ASSERT_INT8_EQUAL(max_i8(0, -1), 0);
	ASSERT_INT8_EQUAL(max_i8(0, 0), 0);
	ASSERT_INT8_EQUAL(max_i8(0, 1), 1);
	ASSERT_INT8_EQUAL(max_i8(0, INT8_MAX), INT8_MAX);

	ASSERT_INT8_EQUAL(max_i8(1, INT8_MIN), 1);
	ASSERT_INT8_EQUAL(max_i8(1, -1), 1);
	ASSERT_INT8_EQUAL(max_i8(1, 0), 1);
	ASSERT_INT8_EQUAL(max_i8(1, 1), 1);
	ASSERT_INT8_EQUAL(max_i8(1, INT8_MAX), INT8_MAX);

	ASSERT_INT8_EQUAL(max_i8(INT8_MAX, INT8_MIN), INT8_MAX);
	ASSERT_INT8_EQUAL(max_i8(INT8_MAX, -1), INT8_MAX);
	ASSERT_INT8_EQUAL(max_i8(INT8_MAX, 0), INT8_MAX);
	ASSERT_INT8_EQUAL(max_i8(INT8_MAX, 1), INT8_MAX);
	ASSERT_INT8_EQUAL(max_i8(INT8_MAX, INT8_MAX), INT8_MAX);
}

TEST(min_u8_tests, "Minimum uint8_t")
{
	ASSERT_UINT8_EQUAL(min_u8(0U, 0U), 0U);
	ASSERT_UINT8_EQUAL(min_u8(0U, 1U), 0U);
	ASSERT_UINT8_EQUAL(min_u8(0U, UINT8_MAX), 0U);

	ASSERT_UINT8_EQUAL(min_u8(1U, 0U), 0U);
	ASSERT_UINT8_EQUAL(min_u8(1U, 1U), 1U);
	ASSERT_UINT8_EQUAL(min_u8(1U, UINT8_MAX), 1U);

	ASSERT_UINT8_EQUAL(min_u8(UINT8_MAX, 0U), 0U);
	ASSERT_UINT8_EQUAL(min_u8(UINT8_MAX, 1U), 1U);
	ASSERT_UINT8_EQUAL(min_u8(UINT8_MAX, UINT8_MAX), UINT8_MAX);
}

TEST(max_u8_tests, "Maximum uint8_t")
{
	ASSERT_UINT8_EQUAL(max_u8(0U, 0U), 0U);
	ASSERT_UINT8_EQUAL(max_u8(0U, 1U), 1U);
	ASSERT_UINT8_EQUAL(max_u8(0U, UINT8_MAX), UINT8_MAX);

	ASSERT_UINT8_EQUAL(max_u8(1U, 0U), 1U);
	ASSERT_UINT8_EQUAL(max_u8(1U, 1U), 1U);
	ASSERT_UINT8_EQUAL(max_u8(1U, UINT8_MAX), UINT8_MAX);

	ASSERT_UINT8_EQUAL(max_u8(UINT8_MAX, 0U), UINT8_MAX);
	ASSERT_UINT8_EQUAL(max_u8(UINT8_MAX, 1U), UINT8_MAX);
	ASSERT_UINT8_EQUAL(max_u8(UINT8_MAX, UINT8_MAX), UINT8_MAX);
}

TEST(min_i16_tests, "Minimum int16_t")
{
	ASSERT_INT16_EQUAL(min_i16(INT16_MIN, INT16_MIN), INT16_MIN);
	ASSERT_INT16_EQUAL(min_i16(INT16_MIN, -1), INT16_MIN);
	ASSERT_INT16_EQUAL(min_i16(INT16_MIN, 0), INT16_MIN);
	ASSERT_INT16_EQUAL(min_i16(INT16_MIN, 1), INT16_MIN);
	ASSERT_INT16_EQUAL(min_i16(INT16_MIN, INT16_MAX), INT16_MIN);

	ASSERT_INT16_EQUAL(min_i16(-1, INT16_MIN), INT16_MIN);
	ASSERT_INT16_EQUAL(min_i16(-1, -1), -1);
	ASSERT_INT16_EQUAL(min_i16(-1, 0), -1);
	ASSERT_INT16_EQUAL(min_i16(-1, 1), -1);
	ASSERT_INT16_EQUAL(min_i16(-1, INT16_MAX), -1);

	ASSERT_INT16_EQUAL(min_i16(0, INT16_MIN), INT16_MIN);
	ASSERT_INT16_EQUAL(min_i16(0, -1), -1);
	ASSERT_INT16_EQUAL(min_i16(0, 0), 0);
	ASSERT_INT16_EQUAL(min_i16(0, 1), 0);
	ASSERT_INT16_EQUAL(min_i16(0, INT16_MAX), 0);

	ASSERT_INT16_EQUAL(min_i16(1, INT16_MIN), INT16_MIN);
	ASSERT_INT16_EQUAL(min_i16(1, -1), -1);
	ASSERT_INT16_EQUAL(min_i16(1, 0), 0);
	ASSERT_INT16_EQUAL(min_i16(1, 1), 1);
	ASSERT_INT16_EQUAL(min_i16(1, INT16_MAX), 1);

	ASSERT_INT16_EQUAL(min_i16(INT16_MAX, INT16_MIN), INT16_MIN);
	ASSERT_INT16_EQUAL(min_i16(INT16_MAX, -1), -1);
	ASSERT_INT16_EQUAL(min_i16(INT16_MAX, 0), 0);
	ASSERT_INT16_EQUAL(min_i16(INT16_MAX, 1), 1);
	ASSERT_INT16_EQUAL(min_i16(INT16_MAX, INT16_MAX), INT16_MAX);
}

TEST(max_i16_tests, "Maximum int16_t")
{
	ASSERT_INT16_EQUAL(max_i16(INT16_MIN, INT16_MIN), INT16_MIN);
	ASSERT_INT16_EQUAL(max_i16(INT16_MIN, -1), -1);
	ASSERT_INT16_EQUAL(max_i16(INT16_MIN, 0), 0);
	ASSERT_INT16_EQUAL(max_i16(INT16_MIN, 1), 1);
	ASSERT_INT16_EQUAL(max_i16(INT16_MIN, INT16_MAX), INT16_MAX);

	ASSERT_INT16_EQUAL(max_i16(-1, INT16_MIN), -1);
	ASSERT_INT16_EQUAL(max_i16(-1, -1), -1);
	ASSERT_INT16_EQUAL(max_i16(-1, 0), 0);
	ASSERT_INT16_EQUAL(max_i16(-1, 1), 1);
	ASSERT_INT16_EQUAL(max_i16(-1, INT16_MAX), INT16_MAX);

	ASSERT_INT16_EQUAL(max_i16(0, INT16_MIN), 0);
	ASSERT_INT16_EQUAL(max_i16(0, -1), 0);
	ASSERT_INT16_EQUAL(max_i16(0, 0), 0);
	ASSERT_INT16_EQUAL(max_i16(0, 1), 1);
	ASSERT_INT16_EQUAL(max_i16(0, INT16_MAX), INT16_MAX);

	ASSERT_INT16_EQUAL(max_i16(1, INT16_MIN), 1);
	ASSERT_INT16_EQUAL(max_i16(1, -1), 1);
	ASSERT_INT16_EQUAL(max_i16(1, 0), 1);
	ASSERT_INT16_EQUAL(max_i16(1, 1), 1);
	ASSERT_INT16_EQUAL(max_i16(1, INT16_MAX), INT16_MAX);

	ASSERT_INT16_EQUAL(max_i16(INT16_MAX, INT16_MIN), INT16_MAX);
	ASSERT_INT16_EQUAL(max_i16(INT16_MAX, -1), INT16_MAX);
	ASSERT_INT16_EQUAL(max_i16(INT16_MAX, 0), INT16_MAX);
	ASSERT_INT16_EQUAL(max_i16(INT16_MAX, 1), INT16_MAX);
	ASSERT_INT16_EQUAL(max_i16(INT16_MAX, INT16_MAX), INT16_MAX);
}

TEST(min_u16_tests, "Minimum uint16_t")
{
	ASSERT_UINT16_EQUAL(min_u16(0U, 0U), 0U);
	ASSERT_UINT16_EQUAL(min_u16(0U, 1U), 0U);
	ASSERT_UINT16_EQUAL(min_u16(0U, UINT16_MAX), 0U);

	ASSERT_UINT16_EQUAL(min_u16(1U, 0U), 0U);
	ASSERT_UINT16_EQUAL(min_u16(1U, 1U), 1U);
	ASSERT_UINT16_EQUAL(min_u16(1U, UINT16_MAX), 1U);

	ASSERT_UINT16_EQUAL(min_u16(UINT16_MAX, 0U), 0U);
	ASSERT_UINT16_EQUAL(min_u16(UINT16_MAX, 1U), 1U);
	ASSERT_UINT16_EQUAL(min_u16(UINT16_MAX, UINT16_MAX), UINT16_MAX);
}

TEST(max_u16_tests, "Maximum uint16_t")
{
	ASSERT_UINT16_EQUAL(max_u16(0U, 0U), 0U);
	ASSERT_UINT16_EQUAL(max_u16(0U, 1U), 1U);
	ASSERT_UINT16_EQUAL(max_u16(0U, UINT16_MAX), UINT16_MAX);

	ASSERT_UINT16_EQUAL(max_u16(1U, 0U), 1U);
	ASSERT_UINT16_EQUAL(max_u16(1U, 1U), 1U);
	ASSERT_UINT16_EQUAL(max_u16(1U, UINT16_MAX), UINT16_MAX);

	ASSERT_UINT16_EQUAL(max_u16(UINT16_MAX, 0U), UINT16_MAX);
	ASSERT_UINT16_EQUAL(max_u16(UINT16_MAX, 1U), UINT16_MAX);
	ASSERT_UINT16_EQUAL(max_u16(UINT16_MAX, UINT16_MAX), UINT16_MAX);
}

TEST(min_i32_tests, "Minimum int32_t")
{
	ASSERT_INT32_EQUAL(min_i32(INT32_MIN, INT32_MIN), INT32_MIN);
	ASSERT_INT32_EQUAL(min_i32(INT32_MIN, -1), INT32_MIN);
	ASSERT_INT32_EQUAL(min_i32(INT32_MIN, 0), INT32_MIN);
	ASSERT_INT32_EQUAL(min_i32(INT32_MIN, 1), INT32_MIN);
	ASSERT_INT32_EQUAL(min_i32(INT32_MIN, INT32_MAX), INT32_MIN);

	ASSERT_INT32_EQUAL(min_i32(-1, INT32_MIN), INT32_MIN);
	ASSERT_INT32_EQUAL(min_i32(-1, -1), -1);
	ASSERT_INT32_EQUAL(min_i32(-1, 0), -1);
	ASSERT_INT32_EQUAL(min_i32(-1, 1), -1);
	ASSERT_INT32_EQUAL(min_i32(-1, INT32_MAX), -1);

	ASSERT_INT32_EQUAL(min_i32(0, INT32_MIN), INT32_MIN);
	ASSERT_INT32_EQUAL(min_i32(0, -1), -1);
	ASSERT_INT32_EQUAL(min_i32(0, 0), 0);
	ASSERT_INT32_EQUAL(min_i32(0, 1), 0);
	ASSERT_INT32_EQUAL(min_i32(0, INT32_MAX), 0);

	ASSERT_INT32_EQUAL(min_i32(1, INT32_MIN), INT32_MIN);
	ASSERT_INT32_EQUAL(min_i32(1, -1), -1);
	ASSERT_INT32_EQUAL(min_i32(1, 0), 0);
	ASSERT_INT32_EQUAL(min_i32(1, 1), 1);
	ASSERT_INT32_EQUAL(min_i32(1, INT32_MAX), 1);

	ASSERT_INT32_EQUAL(min_i32(INT32_MAX, INT32_MIN), INT32_MIN);
	ASSERT_INT32_EQUAL(min_i32(INT32_MAX, -1), -1);
	ASSERT_INT32_EQUAL(min_i32(INT32_MAX, 0), 0);
	ASSERT_INT32_EQUAL(min_i32(INT32_MAX, 1), 1);
	ASSERT_INT32_EQUAL(min_i32(INT32_MAX, INT32_MAX), INT32_MAX);
}

TEST(max_i32_tests, "Maximum int32_t")
{
	ASSERT_INT32_EQUAL(max_i32(INT32_MIN, INT32_MIN), INT32_MIN);
	ASSERT_INT32_EQUAL(max_i32(INT32_MIN, -1), -1);
	ASSERT_INT32_EQUAL(max_i32(INT32_MIN, 0), 0);
	ASSERT_INT32_EQUAL(max_i32(INT32_MIN, 1), 1);
	ASSERT_INT32_EQUAL(max_i32(INT32_MIN, INT32_MAX), INT32_MAX);

	ASSERT_INT32_EQUAL(max_i32(-1, INT32_MIN), -1);
	ASSERT_INT32_EQUAL(max_i32(-1, -1), -1);
	ASSERT_INT32_EQUAL(max_i32(-1, 0), 0);
	ASSERT_INT32_EQUAL(max_i32(-1, 1), 1);
	ASSERT_INT32_EQUAL(max_i32(-1, INT32_MAX), INT32_MAX);

	ASSERT_INT32_EQUAL(max_i32(0, INT32_MIN), 0);
	ASSERT_INT32_EQUAL(max_i32(0, -1), 0);
	ASSERT_INT32_EQUAL(max_i32(0, 0), 0);
	ASSERT_INT32_EQUAL(max_i32(0, 1), 1);
	ASSERT_INT32_EQUAL(max_i32(0, INT32_MAX), INT32_MAX);

	ASSERT_INT32_EQUAL(max_i32(1, INT32_MIN), 1);
	ASSERT_INT32_EQUAL(max_i32(1, -1), 1);
	ASSERT_INT32_EQUAL(max_i32(1, 0), 1);
	ASSERT_INT32_EQUAL(max_i32(1, 1), 1);
	ASSERT_INT32_EQUAL(max_i32(1, INT32_MAX), INT32_MAX);

	ASSERT_INT32_EQUAL(max_i32(INT32_MAX, INT32_MIN), INT32_MAX);
	ASSERT_INT32_EQUAL(max_i32(INT32_MAX, -1), INT32_MAX);
	ASSERT_INT32_EQUAL(max_i32(INT32_MAX, 0), INT32_MAX);
	ASSERT_INT32_EQUAL(max_i32(INT32_MAX, 1), INT32_MAX);
	ASSERT_INT32_EQUAL(max_i32(INT32_MAX, INT32_MAX), INT32_MAX);
}

TEST(min_u32_tests, "Minimum uint32_t")
{
	ASSERT_UINT32_EQUAL(min_u32(0U, 0U), 0U);
	ASSERT_UINT32_EQUAL(min_u32(0U, 1U), 0U);
	ASSERT_UINT32_EQUAL(min_u32(0U, UINT32_MAX), 0U);

	ASSERT_UINT32_EQUAL(min_u32(1U, 0U), 0U);
	ASSERT_UINT32_EQUAL(min_u32(1U, 1U), 1U);
	ASSERT_UINT32_EQUAL(min_u32(1U, UINT32_MAX), 1U);

	ASSERT_UINT32_EQUAL(min_u32(UINT32_MAX, 0U), 0U);
	ASSERT_UINT32_EQUAL(min_u32(UINT32_MAX, 1U), 1U);
	ASSERT_UINT32_EQUAL(min_u32(UINT32_MAX, UINT32_MAX), UINT32_MAX);
}

TEST(max_u32_tests, "Maximum uint32_t")
{
	ASSERT_UINT32_EQUAL(max_u32(0U, 0U), 0U);
	ASSERT_UINT32_EQUAL(max_u32(0U, 1U), 1U);
	ASSERT_UINT32_EQUAL(max_u32(0U, UINT32_MAX), UINT32_MAX);

	ASSERT_UINT32_EQUAL(max_u32(1U, 0U), 1U);
	ASSERT_UINT32_EQUAL(max_u32(1U, 1U), 1U);
	ASSERT_UINT32_EQUAL(max_u32(1U, UINT32_MAX), UINT32_MAX);

	ASSERT_UINT32_EQUAL(max_u32(UINT32_MAX, 0U), UINT32_MAX);
	ASSERT_UINT32_EQUAL(max_u32(UINT32_MAX, 1U), UINT32_MAX);
	ASSERT_UINT32_EQUAL(max_u32(UINT32_MAX, UINT32_MAX), UINT32_MAX);
}

#if defined(INT64_MIN) and defined(INT64_MAX)

TEST(min_i64_tests, "Minimum int64_t")
{
	ASSERT_INT64_EQUAL(min_i64(INT64_MIN, INT64_MIN), INT64_MIN);
	ASSERT_INT64_EQUAL(min_i64(INT64_MIN, -1), INT64_MIN);
	ASSERT_INT64_EQUAL(min_i64(INT64_MIN, 0), INT64_MIN);
	ASSERT_INT64_EQUAL(min_i64(INT64_MIN, 1), INT64_MIN);
	ASSERT_INT64_EQUAL(min_i64(INT64_MIN, INT64_MAX), INT64_MIN);

	ASSERT_INT64_EQUAL(min_i64(-1, INT64_MIN), INT64_MIN);
	ASSERT_INT64_EQUAL(min_i64(-1, -1), -1);
	ASSERT_INT64_EQUAL(min_i64(-1, 0), -1);
	ASSERT_INT64_EQUAL(min_i64(-1, 1), -1);
	ASSERT_INT64_EQUAL(min_i64(-1, INT64_MAX), -1);

	ASSERT_INT64_EQUAL(min_i64(0, INT64_MIN), INT64_MIN);
	ASSERT_INT64_EQUAL(min_i64(0, -1), -1);
	ASSERT_INT64_EQUAL(min_i64(0, 0), 0);
	ASSERT_INT64_EQUAL(min_i64(0, 1), 0);
	ASSERT_INT64_EQUAL(min_i64(0, INT64_MAX), 0);

	ASSERT_INT64_EQUAL(min_i64(1, INT64_MIN), INT64_MIN);
	ASSERT_INT64_EQUAL(min_i64(1, -1), -1);
	ASSERT_INT64_EQUAL(min_i64(1, 0), 0);
	ASSERT_INT64_EQUAL(min_i64(1, 1), 1);
	ASSERT_INT64_EQUAL(min_i64(1, INT64_MAX), 1);

	ASSERT_INT64_EQUAL(min_i64(INT64_MAX, INT64_MIN), INT64_MIN);
	ASSERT_INT64_EQUAL(min_i64(INT64_MAX, -1), -1);
	ASSERT_INT64_EQUAL(min_i64(INT64_MAX, 0), 0);
	ASSERT_INT64_EQUAL(min_i64(INT64_MAX, 1), 1);
	ASSERT_INT64_EQUAL(min_i64(INT64_MAX, INT64_MAX), INT64_MAX);
}

TEST(max_i64_tests, "Maximum int64_t")
{
	ASSERT_INT64_EQUAL(max_i64(INT64_MIN, INT64_MIN), INT64_MIN);
	ASSERT_INT64_EQUAL(max_i64(INT64_MIN, -1), -1);
	ASSERT_INT64_EQUAL(max_i64(INT64_MIN, 0), 0);
	ASSERT_INT64_EQUAL(max_i64(INT64_MIN, 1), 1);
	ASSERT_INT64_EQUAL(max_i64(INT64_MIN, INT64_MAX), INT64_MAX);

	ASSERT_INT64_EQUAL(max_i64(-1, INT64_MIN), -1);
	ASSERT_INT64_EQUAL(max_i64(-1, -1), -1);
	ASSERT_INT64_EQUAL(max_i64(-1, 0), 0);
	ASSERT_INT64_EQUAL(max_i64(-1, 1), 1);
	ASSERT_INT64_EQUAL(max_i64(-1, INT64_MAX), INT64_MAX);

	ASSERT_INT64_EQUAL(max_i64(0, INT64_MIN), 0);
	ASSERT_INT64_EQUAL(max_i64(0, -1), 0);
	ASSERT_INT64_EQUAL(max_i64(0, 0), 0);
	ASSERT_INT64_EQUAL(max_i64(0, 1), 1);
	ASSERT_INT64_EQUAL(max_i64(0, INT64_MAX), INT64_MAX);

	ASSERT_INT64_EQUAL(max_i64(1, INT64_MIN), 1);
	ASSERT_INT64_EQUAL(max_i64(1, -1), 1);
	ASSERT_INT64_EQUAL(max_i64(1, 0), 1);
	ASSERT_INT64_EQUAL(max_i64(1, 1), 1);
	ASSERT_INT64_EQUAL(max_i64(1, INT64_MAX), INT64_MAX);

	ASSERT_INT64_EQUAL(max_i64(INT64_MAX, INT64_MIN), INT64_MAX);
	ASSERT_INT64_EQUAL(max_i64(INT64_MAX, -1), INT64_MAX);
	ASSERT_INT64_EQUAL(max_i64(INT64_MAX, 0), INT64_MAX);
	ASSERT_INT64_EQUAL(max_i64(INT64_MAX, 1), INT64_MAX);
	ASSERT_INT64_EQUAL(max_i64(INT64_MAX, INT64_MAX), INT64_MAX);
}

#endif

#if defined(UINT64_MAX)

TEST(min_u64_tests, "Minimum uint64_t")
{
	ASSERT_UINT64_EQUAL(min_u64(0U, 0U), 0U);
	ASSERT_UINT64_EQUAL(min_u64(0U, 1U), 0U);
	ASSERT_UINT64_EQUAL(min_u64(0U, UINT64_MAX), 0U);

	ASSERT_UINT64_EQUAL(min_u64(1U, 0U), 0U);
	ASSERT_UINT64_EQUAL(min_u64(1U, 1U), 1U);
	ASSERT_UINT64_EQUAL(min_u64(1U, UINT64_MAX), 1U);

	ASSERT_UINT64_EQUAL(min_u64(UINT64_MAX, 0U), 0U);
	ASSERT_UINT64_EQUAL(min_u64(UINT64_MAX, 1U), 1U);
	ASSERT_UINT64_EQUAL(min_u64(UINT64_MAX, UINT64_MAX), UINT64_MAX);
}

TEST(max_u64_tests, "Maximum uint64_t")
{
	ASSERT_UINT64_EQUAL(max_u64(0U, 0U), 0U);
	ASSERT_UINT64_EQUAL(max_u64(0U, 1U), 1U);
	ASSERT_UINT64_EQUAL(max_u64(0U, UINT64_MAX), UINT64_MAX);

	ASSERT_UINT64_EQUAL(max_u64(1U, 0U), 1U);
	ASSERT_UINT64_EQUAL(max_u64(1U, 1U), 1U);
	ASSERT_UINT64_EQUAL(max_u64(1U, UINT64_MAX), UINT64_MAX);

	ASSERT_UINT64_EQUAL(max_u64(UINT64_MAX, 0U), UINT64_MAX);
	ASSERT_UINT64_EQUAL(max_u64(UINT64_MAX, 1U), UINT64_MAX);
	ASSERT_UINT64_EQUAL(max_u64(UINT64_MAX, UINT64_MAX), UINT64_MAX);
}

#endif

TEST(min_ptrdiff_tests, "Minimum ptrdiff_t")
{
	ASSERT_PTRDIFF_EQUAL(min_ptrdiff(PTRDIFF_MIN, PTRDIFF_MIN), PTRDIFF_MIN);
	ASSERT_PTRDIFF_EQUAL(min_ptrdiff(PTRDIFF_MIN, -1), PTRDIFF_MIN);
	ASSERT_PTRDIFF_EQUAL(min_ptrdiff(PTRDIFF_MIN, 0), PTRDIFF_MIN);
	ASSERT_PTRDIFF_EQUAL(min_ptrdiff(PTRDIFF_MIN, 1), PTRDIFF_MIN);
	ASSERT_PTRDIFF_EQUAL(min_ptrdiff(PTRDIFF_MIN, PTRDIFF_MAX), PTRDIFF_MIN);

	ASSERT_PTRDIFF_EQUAL(min_ptrdiff(-1, PTRDIFF_MIN), PTRDIFF_MIN);
	ASSERT_PTRDIFF_EQUAL(min_ptrdiff(-1, -1), -1);
	ASSERT_PTRDIFF_EQUAL(min_ptrdiff(-1, 0), -1);
	ASSERT_PTRDIFF_EQUAL(min_ptrdiff(-1, 1), -1);
	ASSERT_PTRDIFF_EQUAL(min_ptrdiff(-1, PTRDIFF_MAX), -1);

	ASSERT_PTRDIFF_EQUAL(min_ptrdiff(0, PTRDIFF_MIN), PTRDIFF_MIN);
	ASSERT_PTRDIFF_EQUAL(min_ptrdiff(0, -1), -1);
	ASSERT_PTRDIFF_EQUAL(min_ptrdiff(0, 0), 0);
	ASSERT_PTRDIFF_EQUAL(min_ptrdiff(0, 1), 0);
	ASSERT_PTRDIFF_EQUAL(min_ptrdiff(0, PTRDIFF_MAX), 0);

	ASSERT_PTRDIFF_EQUAL(min_ptrdiff(1, PTRDIFF_MIN), PTRDIFF_MIN);
	ASSERT_PTRDIFF_EQUAL(min_ptrdiff(1, -1), -1);
	ASSERT_PTRDIFF_EQUAL(min_ptrdiff(1, 0), 0);
	ASSERT_PTRDIFF_EQUAL(min_ptrdiff(1, 1), 1);
	ASSERT_PTRDIFF_EQUAL(min_ptrdiff(1, PTRDIFF_MAX), 1);

	ASSERT_PTRDIFF_EQUAL(min_ptrdiff(PTRDIFF_MAX, PTRDIFF_MIN), PTRDIFF_MIN);
	ASSERT_PTRDIFF_EQUAL(min_ptrdiff(PTRDIFF_MAX, -1), -1);
	ASSERT_PTRDIFF_EQUAL(min_ptrdiff(PTRDIFF_MAX, 0), 0);
	ASSERT_PTRDIFF_EQUAL(min_ptrdiff(PTRDIFF_MAX, 1), 1);
	ASSERT_PTRDIFF_EQUAL(min_ptrdiff(PTRDIFF_MAX, PTRDIFF_MAX), PTRDIFF_MAX);
}

TEST(max_ptrdiff_tests, "Maximum ptrdiff_t")
{
	ASSERT_PTRDIFF_EQUAL(max_ptrdiff(PTRDIFF_MIN, PTRDIFF_MIN), PTRDIFF_MIN);
	ASSERT_PTRDIFF_EQUAL(max_ptrdiff(PTRDIFF_MIN, -1), -1);
	ASSERT_PTRDIFF_EQUAL(max_ptrdiff(PTRDIFF_MIN, 0), 0);
	ASSERT_PTRDIFF_EQUAL(max_ptrdiff(PTRDIFF_MIN, 1), 1);
	ASSERT_PTRDIFF_EQUAL(max_ptrdiff(PTRDIFF_MIN, PTRDIFF_MAX), PTRDIFF_MAX);

	ASSERT_PTRDIFF_EQUAL(max_ptrdiff(-1, PTRDIFF_MIN), -1);
	ASSERT_PTRDIFF_EQUAL(max_ptrdiff(-1, -1), -1);
	ASSERT_PTRDIFF_EQUAL(max_ptrdiff(-1, 0), 0);
	ASSERT_PTRDIFF_EQUAL(max_ptrdiff(-1, 1), 1);
	ASSERT_PTRDIFF_EQUAL(max_ptrdiff(-1, PTRDIFF_MAX), PTRDIFF_MAX);

	ASSERT_PTRDIFF_EQUAL(max_ptrdiff(0, PTRDIFF_MIN), 0);
	ASSERT_PTRDIFF_EQUAL(max_ptrdiff(0, -1), 0);
	ASSERT_PTRDIFF_EQUAL(max_ptrdiff(0, 0), 0);
	ASSERT_PTRDIFF_EQUAL(max_ptrdiff(0, 1), 1);
	ASSERT_PTRDIFF_EQUAL(max_ptrdiff(0, PTRDIFF_MAX), PTRDIFF_MAX);

	ASSERT_PTRDIFF_EQUAL(max_ptrdiff(1, PTRDIFF_MIN), 1);
	ASSERT_PTRDIFF_EQUAL(max_ptrdiff(1, -1), 1);
	ASSERT_PTRDIFF_EQUAL(max_ptrdiff(1, 0), 1);
	ASSERT_PTRDIFF_EQUAL(max_ptrdiff(1, 1), 1);
	ASSERT_PTRDIFF_EQUAL(max_ptrdiff(1, PTRDIFF_MAX), PTRDIFF_MAX);

	ASSERT_PTRDIFF_EQUAL(max_ptrdiff(PTRDIFF_MAX, PTRDIFF_MIN), PTRDIFF_MAX);
	ASSERT_PTRDIFF_EQUAL(max_ptrdiff(PTRDIFF_MAX, -1), PTRDIFF_MAX);
	ASSERT_PTRDIFF_EQUAL(max_ptrdiff(PTRDIFF_MAX, 0), PTRDIFF_MAX);
	ASSERT_PTRDIFF_EQUAL(max_ptrdiff(PTRDIFF_MAX, 1), PTRDIFF_MAX);
	ASSERT_PTRDIFF_EQUAL(max_ptrdiff(PTRDIFF_MAX, PTRDIFF_MAX), PTRDIFF_MAX);
}

TEST(min_size_tests, "Minimum size_t")
{
	ASSERT_SIZE_EQUAL(min_size(0U, 0U), 0U);
	ASSERT_SIZE_EQUAL(min_size(0U, 1U), 0U);
	ASSERT_SIZE_EQUAL(min_size(0U, SIZE_MAX), 0U);

	ASSERT_SIZE_EQUAL(min_size(1U, 0U), 0U);
	ASSERT_SIZE_EQUAL(min_size(1U, 1U), 1U);
	ASSERT_SIZE_EQUAL(min_size(1U, SIZE_MAX), 1U);

	ASSERT_SIZE_EQUAL(min_size(SIZE_MAX, 0U), 0U);
	ASSERT_SIZE_EQUAL(min_size(SIZE_MAX, 1U), 1U);
	ASSERT_SIZE_EQUAL(min_size(SIZE_MAX, SIZE_MAX), SIZE_MAX);
}

TEST(max_size_tests, "Maximum size_t")
{
	ASSERT_SIZE_EQUAL(max_size(0U, 0U), 0U);
	ASSERT_SIZE_EQUAL(max_size(0U, 1U), 1U);
	ASSERT_SIZE_EQUAL(max_size(0U, SIZE_MAX), SIZE_MAX);

	ASSERT_SIZE_EQUAL(max_size(1U, 0U), 1U);
	ASSERT_SIZE_EQUAL(max_size(1U, 1U), 1U);
	ASSERT_SIZE_EQUAL(max_size(1U, SIZE_MAX), SIZE_MAX);

	ASSERT_SIZE_EQUAL(max_size(SIZE_MAX, 0U), SIZE_MAX);
	ASSERT_SIZE_EQUAL(max_size(SIZE_MAX, 1U), SIZE_MAX);
	ASSERT_SIZE_EQUAL(max_size(SIZE_MAX, SIZE_MAX), SIZE_MAX);
}

TEST(min_intptr_tests, "Minimum intptr_t")
{
	ASSERT_PTRDIFF_EQUAL(min_intptr(INTPTR_MIN, INTPTR_MIN), INTPTR_MIN);
	ASSERT_PTRDIFF_EQUAL(min_intptr(INTPTR_MIN, -1), INTPTR_MIN);
	ASSERT_PTRDIFF_EQUAL(min_intptr(INTPTR_MIN, 0), INTPTR_MIN);
	ASSERT_PTRDIFF_EQUAL(min_intptr(INTPTR_MIN, 1), INTPTR_MIN);
	ASSERT_PTRDIFF_EQUAL(min_intptr(INTPTR_MIN, INTPTR_MAX), INTPTR_MIN);

	ASSERT_PTRDIFF_EQUAL(min_intptr(-1, INTPTR_MIN), INTPTR_MIN);
	ASSERT_PTRDIFF_EQUAL(min_intptr(-1, -1), -1);
	ASSERT_PTRDIFF_EQUAL(min_intptr(-1, 0), -1);
	ASSERT_PTRDIFF_EQUAL(min_intptr(-1, 1), -1);
	ASSERT_PTRDIFF_EQUAL(min_intptr(-1, INTPTR_MAX), -1);

	ASSERT_PTRDIFF_EQUAL(min_intptr(0, INTPTR_MIN), INTPTR_MIN);
	ASSERT_PTRDIFF_EQUAL(min_intptr(0, -1), -1);
	ASSERT_PTRDIFF_EQUAL(min_intptr(0, 0), 0);
	ASSERT_PTRDIFF_EQUAL(min_intptr(0, 1), 0);
	ASSERT_PTRDIFF_EQUAL(min_intptr(0, INTPTR_MAX), 0);

	ASSERT_PTRDIFF_EQUAL(min_intptr(1, INTPTR_MIN), INTPTR_MIN);
	ASSERT_PTRDIFF_EQUAL(min_intptr(1, -1), -1);
	ASSERT_PTRDIFF_EQUAL(min_intptr(1, 0), 0);
	ASSERT_PTRDIFF_EQUAL(min_intptr(1, 1), 1);
	ASSERT_PTRDIFF_EQUAL(min_intptr(1, INTPTR_MAX), 1);

	ASSERT_PTRDIFF_EQUAL(min_intptr(INTPTR_MAX, INTPTR_MIN), INTPTR_MIN);
	ASSERT_PTRDIFF_EQUAL(min_intptr(INTPTR_MAX, -1), -1);
	ASSERT_PTRDIFF_EQUAL(min_intptr(INTPTR_MAX, 0), 0);
	ASSERT_PTRDIFF_EQUAL(min_intptr(INTPTR_MAX, 1), 1);
	ASSERT_PTRDIFF_EQUAL(min_intptr(INTPTR_MAX, INTPTR_MAX), INTPTR_MAX);
}

TEST(max_intptr_tests, "Maximum intptr_t")
{
	ASSERT_PTRDIFF_EQUAL(max_intptr(INTPTR_MIN, INTPTR_MIN), INTPTR_MIN);
	ASSERT_PTRDIFF_EQUAL(max_intptr(INTPTR_MIN, -1), -1);
	ASSERT_PTRDIFF_EQUAL(max_intptr(INTPTR_MIN, 0), 0);
	ASSERT_PTRDIFF_EQUAL(max_intptr(INTPTR_MIN, 1), 1);
	ASSERT_PTRDIFF_EQUAL(max_intptr(INTPTR_MIN, INTPTR_MAX), INTPTR_MAX);

	ASSERT_PTRDIFF_EQUAL(max_intptr(-1, INTPTR_MIN), -1);
	ASSERT_PTRDIFF_EQUAL(max_intptr(-1, -1), -1);
	ASSERT_PTRDIFF_EQUAL(max_intptr(-1, 0), 0);
	ASSERT_PTRDIFF_EQUAL(max_intptr(-1, 1), 1);
	ASSERT_PTRDIFF_EQUAL(max_intptr(-1, INTPTR_MAX), INTPTR_MAX);

	ASSERT_PTRDIFF_EQUAL(max_intptr(0, INTPTR_MIN), 0);
	ASSERT_PTRDIFF_EQUAL(max_intptr(0, -1), 0);
	ASSERT_PTRDIFF_EQUAL(max_intptr(0, 0), 0);
	ASSERT_PTRDIFF_EQUAL(max_intptr(0, 1), 1);
	ASSERT_PTRDIFF_EQUAL(max_intptr(0, INTPTR_MAX), INTPTR_MAX);

	ASSERT_PTRDIFF_EQUAL(max_intptr(1, INTPTR_MIN), 1);
	ASSERT_PTRDIFF_EQUAL(max_intptr(1, -1), 1);
	ASSERT_PTRDIFF_EQUAL(max_intptr(1, 0), 1);
	ASSERT_PTRDIFF_EQUAL(max_intptr(1, 1), 1);
	ASSERT_PTRDIFF_EQUAL(max_intptr(1, INTPTR_MAX), INTPTR_MAX);

	ASSERT_PTRDIFF_EQUAL(max_intptr(INTPTR_MAX, INTPTR_MIN), INTPTR_MAX);
	ASSERT_PTRDIFF_EQUAL(max_intptr(INTPTR_MAX, -1), INTPTR_MAX);
	ASSERT_PTRDIFF_EQUAL(max_intptr(INTPTR_MAX, 0), INTPTR_MAX);
	ASSERT_PTRDIFF_EQUAL(max_intptr(INTPTR_MAX, 1), INTPTR_MAX);
	ASSERT_PTRDIFF_EQUAL(max_intptr(INTPTR_MAX, INTPTR_MAX), INTPTR_MAX);
}

TEST(min_uintptr_tests, "Minimum uintptr_t")
{
	ASSERT_SIZE_EQUAL(min_uintptr(0U, 0U), 0U);
	ASSERT_SIZE_EQUAL(min_uintptr(0U, 1U), 0U);
	ASSERT_SIZE_EQUAL(min_uintptr(0U, UINTPTR_MAX), 0U);

	ASSERT_SIZE_EQUAL(min_uintptr(1U, 0U), 0U);
	ASSERT_SIZE_EQUAL(min_uintptr(1U, 1U), 1U);
	ASSERT_SIZE_EQUAL(min_uintptr(1U, UINTPTR_MAX), 1U);

	ASSERT_SIZE_EQUAL(min_uintptr(UINTPTR_MAX, 0U), 0U);
	ASSERT_SIZE_EQUAL(min_uintptr(UINTPTR_MAX, 1U), 1U);
	ASSERT_SIZE_EQUAL(min_uintptr(UINTPTR_MAX, UINTPTR_MAX), UINTPTR_MAX);
}

TEST(max_uintptr_tests, "Maximum uintptr_t")
{
	ASSERT_SIZE_EQUAL(max_uintptr(0U, 0U), 0U);
	ASSERT_SIZE_EQUAL(max_uintptr(0U, 1U), 1U);
	ASSERT_SIZE_EQUAL(max_uintptr(0U, UINTPTR_MAX), UINTPTR_MAX);

	ASSERT_SIZE_EQUAL(max_uintptr(1U, 0U), 1U);
	ASSERT_SIZE_EQUAL(max_uintptr(1U, 1U), 1U);
	ASSERT_SIZE_EQUAL(max_uintptr(1U, UINTPTR_MAX), UINTPTR_MAX);

	ASSERT_SIZE_EQUAL(max_uintptr(UINTPTR_MAX, 0U), UINTPTR_MAX);
	ASSERT_SIZE_EQUAL(max_uintptr(UINTPTR_MAX, 1U), UINTPTR_MAX);
	ASSERT_SIZE_EQUAL(max_uintptr(UINTPTR_MAX, UINTPTR_MAX), UINTPTR_MAX);
}

int main(void)
{
	DEFINE_LIST_OF_TESTS(tests) {
		min_char_tests,
		max_char_tests,
		min_schar_tests,
		max_schar_tests,
		min_uchar_tests,
		max_uchar_tests,
		min_short_tests,
		max_short_tests,
		min_ushort_tests,
		max_ushort_tests,
		min_int_tests,
		max_int_tests,
		min_uint_tests,
		max_uint_tests,
		min_long_tests,
		max_long_tests,
		min_ulong_tests,
		max_ulong_tests,
		min_llong_tests,
		max_llong_tests,
		min_ullong_tests,
		max_ullong_tests,
		min_i8_tests,
		max_i8_tests,
		min_u8_tests,
		max_u8_tests,
		min_i16_tests,
		max_i16_tests,
		min_u16_tests,
		max_u16_tests,
		min_i32_tests,
		max_i32_tests,
		min_u32_tests,
		max_u32_tests,
		min_i64_tests,
		max_i64_tests,
		min_u64_tests,
		max_u64_tests,
		min_ptrdiff_tests,
		max_ptrdiff_tests,
		min_size_tests,
		max_size_tests,
		min_intptr_tests,
		max_intptr_tests,
		min_uintptr_tests,
		max_uintptr_tests
	};

	PRINT_FILE_NAME();
	RUN_TESTS(tests);
	PRINT_TEST_STATISTICS(tests);
	return TEST_RESULT_ERROR_CODE;
}
